image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  PLATFORMIO_CACHE_DIR: "$CI_PROJECT_DIR/.platformio-cache"

cache:
  paths:
    - .pip-cache/
    - .platformio-cache/

stages:
 - build_test
 - build_all

build_test:
  stage: build_test
  before_script:
    - "pip install -U platformio"
  script: "pio run --environment esp32-master-sword-debug"

build_all:
  stage: build_all
  before_script:
    - "pip install -U platformio"
    - "mkdir -p $CI_PROJECT_DIR/tmp/build"
  script: "platformio ci --build-dir=\"$CI_PROJECT_DIR/tmp/build\" --keep-build-dir --project-conf platformio.ini"
  variables: {PLATFORMIO_CI_SRC: "src"}
  artifacts:
    paths:
    - $CI_PROJECT_DIR/tmp/build/.pio/build/esp32-master-sword-release/firmware.elf
    - $CI_PROJECT_DIR/tmp/build/.pio/build/esp32-master-sword-release/firmware.bin
    - $CI_PROJECT_DIR/tmp/build/.pio/build/esp32-master-sword-debug/firmware.elf
    - $CI_PROJECT_DIR/tmp/build/.pio/build/esp32-master-sword-debug/firmware.bin
    expire_in: 1 week
